### ISSUE TITLE
'Trip' in relation to 'Sustained Operation Of A Vehicle' in AutonomousVehicles ontology

### ISSUE THREAD

**Issue by kulicki** [edmcouncil/auto#14]
As an explanatory note on 'Trip' says: "Performance of the DDT during a given trip may be accomplished in whole or in part by a driver, driving automation system, or both." the relation should not be of type 'exactly 1'. I would rather put 'some.' 

I assume here that instances of class 'Operate Motor Vehicle' and its subclass  'Sustained Operation Of A Vehicle' are homogeneous because they are in the whole of a certain level of autonomy. Then a trip in which the level of autonomy is changing should be related to many different instances of 'Operate Motor Vehicle.'

**Comment by trypuz** [comment]
@kulicki, I agree in general, but IMO only one Sustained Operation Of A Vehicle type event (the "biggest" one!) constitutes the trip. The event may have parts, so it is exactly as you wrote.

**Comment by trypuz** [comment]
But... now I'm thinking loudly that we may have a problem with agency attribution in the case of  Sustained Operation Of A Vehicle type event that, for example, has 2 parts; the first one is carried out by ADS and the second one by a human. To be discussed.

**Comment by mereolog** [comment]
AutonomousVehicles was removed.
