### ISSUE TITLE
Duplication of automation levels

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/auto#6]
[In the current version of auto-dev](https://github.com/edmcouncil/auto/commit/a34d85a3753091ba2bc12aae12112e21fd41d5bf) automation levels are modelled both as classes and as named individuals, e.g., the level of high driving automation is modelled as:
- as class in AutonomousVehicles.rdf <owl:Class rdf:about="&auto-de-av;HighDrivingAutomation">
- as named individual in TrafficCrashes.rdf <owl:NamedIndividual rdf:about="&auto-de-tc;HighDrivingAutomation">
As a result their definitions, explanatory notes, etc. are duplicated, which makes the ontology [wet](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

I think that either invididuals or classes must be removed.

**Comment by kulicki** [comment]
I have some doubts here. On the ideological level some people [defend humidity](https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction).
As for this particular issue we have now in the ontology Automation levels as subclasses of Activity, more precisely the activity of 'Operate Motor Vehicle'. That alows us to define the relation between those levels and 'Dynamic Driving Task Subtasks'. 

On the other hand I expect the need for labeling cars with their capacity for autonomous driving. It seems to me that it would be quite complex to use Activities for that purpose. Thus maybe a bunch of individuals or a subclasses of vehicles (possibly defined by activities) would be useful.

**Comment by mereolog** [comment]
Fair enough, you want it wet, you will have it wet.

What about this duplication then?
https://spec.edmcouncil.org/auto/ontology/DE/AutonomousVehicles/NoAutomation
https://spec.edmcouncil.org/auto/ontology/DE/TrafficCrashes/NoAutomation

These two have almost the same metadata, so perhaps they are genuine duplicates that need to be dried.

And there are more cases like this.
